### PR TITLE
mongodb client: move maxPoolSize, maxConnIdleTime to mongo client

### PR DESCRIPTION
**Pull request by jkralik**

### CODE REVIEW

**Review by ondrejtomcik — APPROVED** [review]

**Comment by ondrejtomcik** [comment]
before merging please update docs and add here link to PR

**Comment by Danielius1922** [comment]
Code is OK, but you've reverted the `googleapis` submodule back to December version, just remove the dependency/googleapis file from the commit.

**Comment by jkralik** [comment]
> Code is OK, but you've reverted the `googleapis` submodule back to December version, just remove the dependency/googleapis file from the commit.

Fixed

**Comment by jkralik** [comment]
Update doc: https://github.com/plgd-dev/www/pull/43

**Pull request merged**
