### PR TITLE
http-gateway/web: Enhanced Device Provisioning and Certificate Management

### PR DESCRIPTION
**Pull request by jkralik**
This pull request introduces a series of significant enhancements across the `http-gateway/web` project, focusing on improving the user experience and system functionality through new features, refactoring, and bug fixes.

#### New Features
- **Enhanced Certificate Management**: Introduced new UI components and logic to streamline certificate operations, making management more intuitive and efficient.
- **Device Provisioning Service**: Launched a new user interface for device provisioning, including advanced management features for linked hubs and TLS configuration.
- **Expanded Device Details**: Added new tabs in the device details view to provide comprehensive information on certificates and provisioning records.
- **Internationalization**: Enhanced support for multiple languages across new UI elements, improving accessibility for global users.
- **New Routing**: Implemented new routes for device provisioning and certificates, optimizing navigation and improving page load times through lazy loading.

#### Refactor
- **Layout Updates**: Improved the usability and flexibility of the AppLayout and PageLayout components, enhancing the overall user interface.
- **Device Provisioning Module**: Refactored the device provisioning module for better data handling and form management, ensuring smoother operations.

#### Style
- **UI Enhancements**: Introduced new styles and utility functions across various modules to enhance the visual appeal and user interaction.

#### Tests
- **Testing Enhancements**: Added new test identifiers to improve the coverage and robustness of automated tests.

#### Chores
- **Project Dependencies**: Updated the commit hashes for subprojects related to shared UI components, ensuring compatibility and stability.

#### Bug Fixes
- **Notification Handling**: Fixed issues related to error notification IDs in the linked hubs, certificates, and provisioning records sections.
- **UI Corrections**: Addressed a minor issue with the subtitle property assignment in the RemoteClientsListPage, ensuring consistency across different views.

### CODE REVIEW

**Comment by jkralik** [comment]
@coderabbitai review

**Review by PatrikMatiasko — APPROVED** [review]

**Comment by jkralik** [comment]
@coderabbitai create pull request description

**Comment by jkralik** [comment]
> Tip
> 
> For best results, initiate chat on the files or code changes.
> 
> @jkralik, based on the changes detailed in the PR, here's a draft for the pull request description:
> 
> ### Pull Request Description
> This pull request introduces significant enhancements across the `http-gateway/web` project, focusing on improving the management and provisioning of certificates, configuration handling, and device provisioning processes.
> 
> #### Key Changes:
> * **Certificates Management**: Enhanced the handling of certificates with new properties and functions such as `deleteCertificatesApi`, `getConfig`, and `getWellKnow`. A new component `CertificatesList` has been added to manage certificate operations effectively.
> * **Configuration Enhancements**: Improved configuration navigation and state management through the use of `generatePath` and updated state initialization for theme settings in `PreviewApp`.
> * **Device Provisioning**: Streamlined the device provisioning process with new components like `DetailFromChunk2` and `DetailFromChunk3` for better management of certificate details and pre-shared key settings. The enrollment process has been refined with new steps and improved form data management.
> 
> These updates aim to enhance the functionality, usability, and maintainability of the platform, ensuring a smoother operation and better user experience.
> 
> Please review this draft and let me know if there are any adjustments or additional details you would like to include.

@coderabbitai make it more oriented to features like new UI for "device provisioning service" and other staff as bugfixes without mention function, properties ...

Similar to style:
## New Features
- Added new configuration options for resolving dependencies in the project setup.
- Enhanced certificate management with new UI components, messages, and logic.
- Introduced comprehensive updates for device provisioning, including new components for managing linked hubs and TLS configuration.
- Expanded device details functionality with new tabs for certificates and provisioning records.
- Added internationalization support for various new UI elements.
- Implemented new routes for device provisioning, certificates, and linked hubs, including lazy-loaded pages for improved performance.
## Refactor
- Updated AppLayout and PageLayout components for improved usability and flexibility.
- Refactored DeviceProvisioning module for better form management and data handling.
## Style
- Added styles and utility functions across multiple modules for an enhanced user experience.
## Tests
- Added new test IDs for improved testing capabilities.
## Chores
- Updated subproject commit hash for shared UI components.
## Bug Fixes
- Fixed error notification IDs for linked hubs, certificates, and provisioning records.
- Addressed an issue with subTitle property assignment in RemoteClientsListPage.
...

**Comment by jkralik** [comment]
@coderabbitai create title for this pull request

**Pull request merged**
